version: '3'
services:
    nginx:
        container_name: some-nginx
        image: 'nginx:1.13'
        restart: always
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - './nginx/conf.d:/etc/nginx/conf.d'
        depends_on:
            - app

    app:
        restart: on-failure
        build: ./app
        working_dir: /app
        volumes:
            - './app:/app'
            - '~/.m2:/root/.m2'
        expose:
            - '8080'
        command: 'mvn clean spring-boot:run'
        depends_on:
            - db

    db:
        image: 'mysql:5.7'
        restart: always
        environment:
            MYSQL_DATABASE: test
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: password1
        ports:
            - '3306:3306'
        expose:
            - '3306'
        volumes:
            - 'my-db:/var/lib/mysql'
            - ./resources/sql-scripts/startup.sql:/docker-entrypoint-initdb.d/startup.sql
volumes:
    my-db: null
